name: uploadandscan

on: push

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
          architecture: x64
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Review artifacts
        run: ls target
      - name: Upload jar
        uses: actions/upload-artifact@v3
        with:
         name: webgoat
         path: target/webgoat-2023.4.jar
         if-no-files-found: warn
  Upload-and-Scan:
    needs: Build
    runs-on: ubuntu-latest
    steps:
    - name: Download jar
      uses: actions/download-artifact@v3
      with:
        name: webgoat
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
    - name: Create folder
      run: mkdir app
    - name: Move artifact
      run: mv webgoat-2023.4.jar app
    - name: Upload and scan
      uses: veracode/veracode-uploadandscan-action@master 
      with: 
        appname: 'WebGoat-2023.4'
        createprofile: 'true'
        filepath: 'app'
        vid: "3848a424a18113931339cf47e3b6203e"
        vkey: "3f808860367da0428092fa323c61981f20c74e5a78a1cf9d33e99be08aeb9b1f788c4119df74d6d6cace3296bf3681286d08fdfc7df91fdb4f6c2db7eb41c174"
        scantimeout: 15
        exclude: '*.js'
        include: '*.jar'
        criticality: 'VeryLow'
